### ISSUE TITLE
Parasyte

### ISSUE THREAD

**Issue by Kisioj** [steward-fu/mmiyoo#1]
Hey, i want to run pygame games on Miyoo stock os. I browsed web and found out that I need parasyte. The only link I found is pointing at this repo: https://github.com/steward-fu/mmiyoo/releases/download/stock/parasyte_20220125.zip but isn't available. How can I download it?

**Comment by steward-fu** [comment]
All files are archived in : https://github.com/steward-fu/website/releases/tag/miyoo-mini
